export const placeTypeToEmoji = {
  restaurant: '🍽️',
  food: '🍽️',
  meal_takeaway: '🥡',
  meal_delivery: '🚚',
  bakery: '🥖',
  cafe: '☕',
  bar: '🍺',
  night_club: '🌃',
  grocery_or_supermarket: '🛒',
  supermarket: '🛒',
  convenience_store: '🏪',
  gas_station: '⛽',
  hospital: '🏥',
  pharmacy: '💊',
  doctor: '👨‍⚕️',
  dentist: '🦷',
  veterinary_care: '🐕',
  bank: '🏦',
  atm: '💳',
  school: '🏫',
  university: '🎓',
  library: '📚',
  church: '⛪',
  mosque: '🕌',
  synagogue: '🕍',
  hindu_temple: '🛕',
  park: '🌳',
  amusement_park: '🎢',
  zoo: '🦁',
  aquarium: '🐠',
  museum: '🏛️',
  art_gallery: '🎨',
  movie_theater: '🎬',
  bowling_alley: '🎳',
  gym: '💪',
  spa: '🧘',
  beauty_salon: '💄',
  hair_care: '💇',
  clothing_store: '👕',
  shoe_store: '👟',
  jewelry_store: '💎',
  electronics_store: '📱',
  book_store: '📖',
  pet_store: '🐾',
  florist: '🌺',
  hardware_store: '🔨',
  home_goods_store: '🏠',
  furniture_store: '🛋️',
  car_dealer: '🚗',
  car_rental: '🚙',
  car_repair: '🔧',
  car_wash: '🚿',
  parking: '🅿️',
  subway_station: '🚇',
  train_station: '🚂',
  bus_station: '🚌',
  airport: '✈️',
  taxi_stand: '🚕',
  bicycle_store: '🚲',
  storage: '📦',
  moving_company: '📦',
  laundry: '👕',
  post_office: '📮',
  fire_station: '🚒',
  police: '👮',
  courthouse: '⚖️',
  city_hall: '🏛️',
  embassy: '🏢',
  tourist_attraction: '📍',
  travel_agency: '🧳',
  lodging: '🏨',
  rv_park: '🚐',
  campground: '⛺',
  cemetery: '🪦',
  funeral_home: '🕯️',
  establishment: '🏢',
  point_of_interest: '📍',
};

export const defaultEmoji = '📍';

export const getEmojiForPlaceType = (types) => {
  if (!types || !Array.isArray(types)) return defaultEmoji;

  for (const type of types) {
    if (placeTypeToEmoji[type]) {
      return placeTypeToEmoji[type];
    }
  }

  return defaultEmoji;
};