name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Setup pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0

      - name: Setup Node from .nvmrc
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create .env file
        run: |
          cat > .env << EOF
          REACT_APP_FIREBASE_API_KEY=${{ vars.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN=${{ vars.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID=${{ vars.REACT_APP_FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET=${{ vars.REACT_APP_FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ vars.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID=${{ vars.REACT_APP_FIREBASE_APP_ID }}
          REACT_APP_GOOGLE_MAPS_API_KEY=${{ vars.REACT_APP_GOOGLE_MAPS_API_KEY }}
          REACT_APP_GOOGLE_MAP_ID=${{ vars.REACT_APP_GOOGLE_MAP_ID }}
          EOF

      - name: Build
        run: pnpm build

      - name: Install markdown-to-html-cli
        run: npm install -g markdown-to-html-cli

      - name: Create policies output directory
        run: mkdir -p build/policies

      - name: Convert policies to HTML
        run: |
          npx markdown-to-html-cli policies/privacy-policy.md --output build/policies/privacy-policy.html --no-dark-mode --title "Praytic Privacy Statement"
          npx markdown-to-html-cli policies/terms-of-service.md --output build/policies/terms-of-service.html --no-dark-mode --title "Praytic Terms of Service"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/370798368805/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider
          service_account: github-actions-deployer@praytic-global-473807.iam.gserviceaccount.com

      - name: Upload to Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: 'build'
          destination: 'places-bucket-e721ffe'
          parent: false
          process_gcloudignore: false
